### PR TITLE
Fix python 3.10.1 bug

### PR DESCRIPTION
**Pull request by aglavic**
Proposed solution to #71 that takes care of the signature change in `dataclasses._field_init`.

### CODE REVIEW

**Review by bmaranville — APPROVED** [review]
I agree that this will address the issue for now, though the private method being called (not part of the public API) could be changed again at any time.  Maybe we can put in a todo to try to re-implement using public methods?

**Comment by andyfaff** [comment]
The internals of dataclasses are an unknown field to me. Things breaking when Python changes their internal implementation does indicate that our implementation may be fragile. However, I think this needs to be merged coz otherwise we can't use orsopy on 3.10.

@bmaranville, do you have an idea for a re-implementation?

**Comment by andyfaff** [comment]
There was a reason why we needed to reimplement those private methods, can anyone remember what it was?

**Comment by andyfaff** [comment]
@aglavic, could you do another alpha release of orsopy so the version on PyPI works on 3.10?

**Comment by bmaranville** [comment]
I think the group voted and it was agreed we would allow users to add extra attributes to header classes that are not in the schema (but will still be serialized and deserialized).  Dataclasses do not support this out of the box, and so we are extending/overriding the native dataclasses functions.

**Comment by aglavic** [comment]
> @aglavic, could you do another alpha release of orsopy so the version on PyPI works on 3.10?

I've created PR #75 for the release, as we discussed in the last meeting. As we are still in Alpha I directly merged that PR and created the version tag to release on PyPI. You should be able to update.

**Pull request merged**
