### PR TITLE
Merge slddb into orsopy

### PR DESCRIPTION
**Pull request by aglavic**
Transferred and integrated slddb into orsopy.

Will be reviewed after the style guidelines PR #64 is merged.

### CODE REVIEW

**Comment by aglavic** [comment]
@andyfaff @bmaranville @arm61 
Can I assume no comment is an acceptance from everybody, or did you miss this PR?

**Review by bmaranville — APPROVED** [review]

**Comment by arm61** [comment]
I am happy with the initial PR as is, but over time I might drop in the PRs of potential changes @aglavic. If that is cool with you?

**Comment by aglavic** [comment]
> I am happy with the initial PR as is, but over time I might drop in the PRs of potential changes @aglavic. If that is cool with you?

Sorry for my issue with the language hear. What do you mean by "drop in the PRs"? Do you want to be included in the reviews or do you plan to submit changes yourself? (Both would be fine with me.)

**Comment by arm61** [comment]
Sorry definitely my bad English and not your understanding. I was going for the latter. New changes/PRs in future.

**Comment by aglavic** [comment]
@bmaranville yes, go ahead and merge it.

**Review by arm61 — APPROVED** [review]

**Comment by aglavic** [comment]
OK, as there were no more comments I'll go ahead and merge this PR.

**Pull request merged**
