### PR TITLE
Meeting minutes form 2021-11-30

### PR DESCRIPTION
**Pull request by arm61**
Please let me know if there is anything you disagree with or I have forgotten.

### CODE REVIEW

**Review by aglavic — APPROVED** [review]
All fine with me

**Review by bmaranville — APPROVED** [review]
These all look good.

**Comment by bmaranville** [comment]
I don't know where to put this suggestion, but I would like to add to our contribution guidelines a hard rule: "no force pushes".  Clearly there will be extraordinary circumstances where this will have to be violated (accidental committing of sensitive material, etc) but in general I think the risk is too great.

**Comment by andyfaff** [comment]
I agree with the no force pushes suggestion.

The only time I would do a force push would be to a feature branch on my fork. When the feature branch arrives in a PR the changes are then obvious. Do you know how much code was mashed?

**Comment by bmaranville** [comment]
I was able to recover the commits like this:
```bash
git fetch origin pull/61/head:metaclass2decorator
git checkout metaclass2decorator
```
as suggested in https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally

**Review by acaruana2009 — APPROVED** [review]

**Comment by arm61** [comment]
I have added something about `force push`. But it looks to me like there is enough approvals, so I will go ahead with it.

**Pull request merged**
